version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: app_${APP_NAME}
    command:
      - |
        composer update
        composer dump-autoload -o
        php artisan config:cache
        php artisan optimize
        php artisan event:cache
        php artisan route:cache
        apache2-foreground
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./app/:/var/www/html/
      - ./docker/app/php.ini:/usr/local/etc/php/conf.d/php.ini

  vite-dev-server:
    image: app_${APP_NAME}
    command:
      - |
        npm update
        npm run dev
    ports:
      - "${VITE_DEV_PORT}:5173"
    volumes:
      - ./app/:/var/www/html/
    depends_on:
      - app